import libmem
from libmem import lm_arch_t as lm_arch_t, lm_inst_t as lm_inst_t, lm_module_t as lm_module_t, lm_process_t as lm_process_t, lm_prot_t as lm_prot_t, lm_segment_t as lm_segment_t, lm_symbol_t as lm_symbol_t, lm_thread_t as lm_thread_t, lm_vmt_t as lm_vmt_t

LM_ARCH_AARCH64: libmem.lm_arch_t
LM_ARCH_ARMV7: libmem.lm_arch_t
LM_ARCH_ARMV7EB: libmem.lm_arch_t
LM_ARCH_ARMV8: libmem.lm_arch_t
LM_ARCH_ARMV8EB: libmem.lm_arch_t
LM_ARCH_GENERIC: libmem.lm_arch_t
LM_ARCH_MAX: libmem.lm_arch_t
LM_ARCH_MIPS: libmem.lm_arch_t
LM_ARCH_MIPS64: libmem.lm_arch_t
LM_ARCH_MIPSEL: libmem.lm_arch_t
LM_ARCH_MIPSEL64: libmem.lm_arch_t
LM_ARCH_PPC32: libmem.lm_arch_t
LM_ARCH_PPC64: libmem.lm_arch_t
LM_ARCH_PPC64LE: libmem.lm_arch_t
LM_ARCH_SPARC: libmem.lm_arch_t
LM_ARCH_SPARC64: libmem.lm_arch_t
LM_ARCH_SPARCEL: libmem.lm_arch_t
LM_ARCH_SYSZ: libmem.lm_arch_t
LM_ARCH_THUMBV7: libmem.lm_arch_t
LM_ARCH_THUMBV7EB: libmem.lm_arch_t
LM_ARCH_THUMBV8: libmem.lm_arch_t
LM_ARCH_THUMBV8EB: libmem.lm_arch_t
LM_ARCH_X64: libmem.lm_arch_t
LM_ARCH_X86: libmem.lm_arch_t
LM_ARCH_X86_16: libmem.lm_arch_t
LM_PROT_R: libmem.lm_prot_t
LM_PROT_RW: libmem.lm_prot_t
LM_PROT_W: libmem.lm_prot_t
LM_PROT_X: libmem.lm_prot_t
LM_PROT_XR: libmem.lm_prot_t
LM_PROT_XRW: libmem.lm_prot_t
LM_PROT_XW: libmem.lm_prot_t

def LM_AllocMemory(*args, **kwargs): ...
def LM_AllocMemoryEx(*args, **kwargs): ...
def LM_Assemble(*args, **kwargs): ...
def LM_AssembleEx(*args, **kwargs): ...
def LM_CodeLength(*args, **kwargs): ...
def LM_CodeLengthEx(*args, **kwargs): ...
def LM_DataScan(*args, **kwargs): ...
def LM_DataScanEx(*args, **kwargs): ...
def LM_DeepPointer(*args, **kwargs): ...
def LM_DeepPointerEx(*args, **kwargs): ...
def LM_DemangleSymbol(*args, **kwargs): ...
def LM_Disassemble(*args, **kwargs): ...
def LM_DisassembleEx(*args, **kwargs): ...
def LM_EnumModules(*args, **kwargs): ...
def LM_EnumModulesEx(*args, **kwargs): ...
def LM_EnumProcesses(*args, **kwargs): ...
def LM_EnumSegments(*args, **kwargs): ...
def LM_EnumSegmentsEx(*args, **kwargs): ...
def LM_EnumSymbols(*args, **kwargs): ...
def LM_EnumSymbolsDemangled(*args, **kwargs): ...
def LM_EnumThreads(*args, **kwargs): ...
def LM_EnumThreadsEx(*args, **kwargs): ...
def LM_FindModule(*args, **kwargs): ...
def LM_FindModuleEx(*args, **kwargs): ...
def LM_FindProcess(*args, **kwargs): ...
def LM_FindSegment(*args, **kwargs): ...
def LM_FindSegmentEx(*args, **kwargs): ...
def LM_FindSymbolAddress(*args, **kwargs): ...
def LM_FindSymbolAddressDemangled(*args, **kwargs): ...
def LM_FreeMemory(*args, **kwargs): ...
def LM_FreeMemoryEx(*args, **kwargs): ...
def LM_GetArchitecture(*args, **kwargs): ...
def LM_GetBits(*args, **kwargs): ...
def LM_GetCommandLine(*args, **kwargs): ...
def LM_GetProcess(*args, **kwargs): ...
def LM_GetProcessEx(*args, **kwargs): ...
def LM_GetSystemBits(*args, **kwargs): ...
def LM_GetThread(*args, **kwargs): ...
def LM_GetThreadEx(*args, **kwargs): ...
def LM_GetThreadProcess(*args, **kwargs): ...
def LM_HookCode(*args, **kwargs): ...
def LM_HookCodeEx(*args, **kwargs): ...
def LM_IsProcessAlive(*args, **kwargs): ...
def LM_LoadModule(*args, **kwargs): ...
def LM_LoadModuleEx(*args, **kwargs): ...
def LM_PatternScan(*args, **kwargs): ...
def LM_PatternScanEx(*args, **kwargs): ...
def LM_ProtMemory(*args, **kwargs): ...
def LM_ProtMemoryEx(*args, **kwargs): ...
def LM_ReadMemory(*args, **kwargs): ...
def LM_ReadMemoryEx(*args, **kwargs): ...
def LM_SetMemory(*args, **kwargs): ...
def LM_SetMemoryEx(*args, **kwargs): ...
def LM_SigScan(*args, **kwargs): ...
def LM_SigScanEx(*args, **kwargs): ...
def LM_UnhookCode(*args, **kwargs): ...
def LM_UnhookCodeEx(*args, **kwargs): ...
def LM_UnloadModule(*args, **kwargs): ...
def LM_UnloadModuleEx(*args, **kwargs): ...
def LM_WriteMemory(*args, **kwargs): ...
def LM_WriteMemoryEx(*args, **kwargs): ...
